### ISSUE TITLE
Compilation d'OpenBLAS CMake sur les Raspberries

### ISSUE THREAD

**Issue by SevenMoor** [hive-entropy/hive-entropy-api#29]
La compilation d'OpenBLAS via CMake ne fonctionne pas sur les Raspberry Pi. Le problème semble lié à l'environnement/aux variables de compilation.

L'erreur renvoyée est:
```/tmp/ccJAcTqg.s: Assembler messages:
/tmp/ccJAcTqg.s:1155: Error: selected processor does not support `dmb ish' in ARM mode
/tmp/ccJAcTqg.s:1402: Error: selected processor does not support `dmb ishst' in ARM mode
```

**Comment by albanLM** [comment]
Les paramètres donnés par CMake au compilateur ne sont pas les bons par défaut.
Le problème est résolu avec la commande :
```bash
cmake -Bbuild/ -S. -DCCOMMON_OPT="-mfpu=vfpv3 -march=armv7-a -mfpu=neon -lpthread"
```
